apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-node-app
spec:
  capacity:
    storage: 90Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" # Adjust the path as needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: shehroz85waseem/metric-node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        volumeMounts:
        - mountPath: "/data" # Adjust the path as needed
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc-node
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 32001
  selector:
    app: node-app